
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

